[package]
name = "ConsoleTitleInjection"
version = "0.1.0"
edition = "2025"

[dependencies]
winapi = { version = "0.3.9", features = ["processthreadsapi", "wincon", "memoryapi", "handleapi", "libloaderapi", "errhandlingapi", "synchapi", "winnt", "minwindef", "ntdef", "basetsd"] }
